language: clojure

services:
  - postgresql

before_script:
  - psql -c 'create database cbook_test;' -U postgres

script:
  - DATABASE_URL="jdbc:postgresql://localhost/cbook_test?user=postgres&password=" lein test

cache:
  directories:
    - target
